Add use-default-language option
edmcouncil/rdf-toolkit pull request #53
Opened 2023-07-28 10:38 UTC by trojczak

2023-07-31 07:12 UTC, mereolog requested changes
Since this introduces a new option, @trojczak could you update the ReadMe file as well?

2023-08-04 08:22 UTC, mereolog commented
Also, and more seriously, mvn clean package yields this:
```
[ERROR] Tests run: 27, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 54.675 s <<< FAILURE! - in org.edmcouncil.rdf_toolkit.writer.SortedRdfXmlWriterTest
[ERROR] shouldUseDefaultSettingsForSerializationOfLiteralsWhenAdditionalSettingsAreNotSet  Time elapsed: 0.015 s  <<< ERROR!
org.edmcouncil.rdf_toolkit.runner.exception.RdfToolkitOptionHandlingException: Source file does not exist: /Users/pawel.garbacz/Documents/edmc/github/edmc/rdf-toolkit/src/test/resources/ontologies/literal/test1.rdf
	at org.edmcouncil.rdf_toolkit.writer.SortedRdfXmlWriterTest.shouldUseDefaultSettingsForSerializationOfLiteralsWhenAdditionalSettingsAreNotSet(SortedRdfXmlWriterTest.java:1119)

[ERROR] shouldUseDefaultSettingsForSerializationOfLiteralsWhenUseDefaultLanguageIsSet  Time elapsed: 0.167 s  <<< ERROR!
org.edmcouncil.rdf_toolkit.runner.exception.RdfToolkitOptionHandlingException: Source file does not exist: /Users/pawel.garbacz/Documents/edmc/github/edmc/rdf-toolkit/src/test/resources/ontologies/literal/test1.rdf
	at org.edmcouncil.rdf_toolkit.writer.SortedRdfXmlWriterTest.shouldUseDefaultSettingsForSerializationOfLiteralsWhenUseDefaultLanguageIsSet(SortedRdfXmlWriterTest.java:1164)

[ERROR] shouldUseDefaultSettingsForSerializationOfLiteralsWhenOverrideLanguageSettingIsSet  Time elapsed: 0.072 s  <<< ERROR!
org.edmcouncil.rdf_toolkit.runner.exception.RdfToolkitOptionHandlingException: Source file does not exist: /Users/pawel.garbacz/Documents/edmc/github/edmc/rdf-toolkit/src/test/resources/ontologies/literal/test1.rdf
	at org.edmcouncil.rdf_toolkit.writer.SortedRdfXmlWriterTest.shouldUseDefaultSettingsForSerializationOfLiteralsWhenOverrideLanguageSettingIsSet(SortedRdfXmlWriterTest.java:1139)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SortedRdfXmlWriterTest.shouldUseDefaultSettingsForSerializationOfLiteralsWhenAdditionalSettingsAreNotSet:1119 » RdfToolkitOptionHandling
[ERROR]   SortedRdfXmlWriterTest.shouldUseDefaultSettingsForSerializationOfLiteralsWhenOverrideLanguageSettingIsSet:1139 » RdfToolkitOptionHandling
[ERROR]   SortedRdfXmlWriterTest.shouldUseDefaultSettingsForSerializationOfLiteralsWhenUseDefaultLanguageIsSet:1164 » RdfToolkitOptionHandling
[INFO] 
[ERROR] Tests run: 85, Failures: 0, Errors: 3, Skipped: 2
```

2024-02-05 09:38 UTC, mereolog approved these changes

2024-02-22 11:02 UTC, raggy2k4 approved these changes

2024-02-22 11:17 UTC, merged